---
- name: Install Python and necessary tools
  ansible.builtin.apt:
    name: "{{ python_debian_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  tags:
    - python

- name: Install additional system Python packages
  ansible.builtin.apt:
    name: "{{ python_system_packages }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: python_system_packages | length > 0
  tags:
    - python

- name: Upgrade pip to latest version
  ansible.builtin.pip:
    name: pip
    state: latest
    executable: pip3
  become: true
  when: python_upgrade_pip | bool
  tags:
    - python
